---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2024 The Linux Foundation <https://linuxfoundation.org>

name: "🏷️ Latest Semantic Tag"

outputs:
  latest-tag:
    description: "Return the latest semantic tag from repository"
    value: ${{ steps.parse-tags.outputs.tag }}

runs:
  using: "composite"
  steps:
    - name: "Report GitHub workflow environment"
      id: vars
      shell: bash
      run: |
        # Report GitHub workflow environment
        echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
        # Report GitHub workflow environment
        echo "Github github.ref_name: ${{ github.ref_name }}"
        echo "Github github.head_ref: ${{ github.head_ref }}"
        echo "Github tag from GITHUB_REF: $RELEASE_VERSION"

    - name: "Validate previous step outputs"
      id: output
      shell: bash
      env:
        RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
      run: |
        # Validate previous step outputs
        echo "Release version: $RELEASE_VERSION"
        echo ${{ steps.vars.outputs.tag }}

    - id: parse-tags
      name: "Extract and report latest semantic tag"
      shell: bash
      run: |
        # Extract and report latest semantic tag
        git tag -l --sort=committerdate | grep -o 'v*.*.*' | sort -r | head -1
