---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2024 The Linux Foundation <https://linuxfoundation.org>

name: "🏷️ Latest Semantic Tag"

outputs:
  TAG:
    description: "Return the latest semantic tag from repository"
    value: ${{ steps.parse-tags.outputs.tag }}
  MISSING:
    description: "Flag set true if no semantic tags found"
    value: ${{ steps.parse-tags.outputs.missing }}

runs:
  using: "composite"
  steps:
    - name: "Fetch Tags"
      shell: bash
      if: steps.capture-environment.outputs.tagged == 'false'
      run: |
        # Workaround for: https://github.com/actions/checkout/issues/1471
        echo "Fetching tags..."
        git fetch --tags

    - name: "Parse Tags"
      id: parse-tags
      shell: bash
      run: |
        # Extract and report latest semantic tag
        if ! (git tag -l | grep 'v*.*.*' > /dev/null); then
          echo "No semantic tags were found"
          echo "missing=true" >> $GITHUB_OUTPUT
          # Set a placeholder value for the tag
          echo "tag=v0.0.0" >> $GITHUB_OUTPUT
        fi
        tag=$(git tag -l --sort=committerdate | grep -o 'v*.*.*' | sort -r | head -1)
        echo "missing=false" >> $GITHUB_OUTPUT
        echo "tag=${tag}" >> $GITHUB_OUTPUT
        echo "Tag: $tag"
