---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2024 The Linux Foundation <https://linuxfoundation.org>

name: "🏷️ Increment Semantic Tag"

inputs:
  TAG:
    description: "The existing semantic tag to be incremented"
    required: true
  TYPE:
    description: "Increment to perform [major|minor|patch]"
    required: false
    default: "patch"

#outputs:
#  INCREMENTED-TAG:
#    # Any single/leading non-numeric "v" character will be stripped
#    description: "The incremented semantic tag [purely numeric]"
#    value: ${{ steps.increment.outputs.tag }}

runs:
  using: "composite"
  steps:
    - name: "Increment tag"
      id: increment
      shell: bash
      run: |
        # Increment semantic tag

        TAG=${{ inputs.TAG }}
        TYPE=${{ inputs.TYPE }}

        # Validate increment type
        if	[ ! "$TYPE" = "major" ] && \
            [ ! "$TYPE" = "minor" ] && \
            [ ! "$TYPE" = "patch" ]; then
           echo "Increment type invalid"; exit 1
        fi

        echo "Input tag: $TAG"
        echo "Increment type: $TYPE"

        if [[ "$TAG" == v* ]]; then
          echo "Converting tag to purely numeric equivalent"
          TAG="${TAG:1}"
        fi

        # Regular expression to match semantic tag
        PATTERN="^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(-((0|[1-9][0-9]*|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9][0-9]*|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*))*))?(\+([0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*))?$"

        # Validate supplied tag
        if ! [[ "$TAG" =~ $PATTERN ]]; then
          echo "Invalid semantic tag"; exit 1
        else
          echo "Numeric tag: $TAG"
        fi
