---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2024 The Linux Foundation <https://linuxfoundation.org>

name: "🏷️ Increment Semantic Tag"

inputs:
  TAG:
    description: "The existing semantic tag to be incremented"
    required: true
  TYPE:
    description: "Increment to perform [major|minor|patch]"
    required: false
    default: "patch"

outputs:
  TAG:
    # A leading non-numeric "v" character will be stripped
    description: "The incremented semantic tag [purely numeric]"
    value: ${{ steps.increment.outputs.tag }}

runs:
  using: "composite"
  steps:
    - name: "Increment tag"
      id: increment
      shell: bash
      run: |
        # Increment semantic tag

        #SHELLCODESTART

        TAG=${{ inputs.TAG }}
        TYPE=${{ inputs.TYPE }}
        if [ -z "$TAG" ] && [ -z "$TYPE" ]; then
          echo "Running from shell script outside GitHub"
          if [ $# -ne 2 ]; then
            echo "Usage:  $0 [tag] [increment-type]"; exit 1
          else
            TAG="$1"
            TYPE="$2"
          fi
        fi

        # Validate increment type
        if	[ ! "$TYPE" = "major" ] && \
            [ ! "$TYPE" = "minor" ] && \
            [ ! "$TYPE" = "patch" ]; then
           echo "Increment type invalid"; exit 1
        fi

        echo "Input tag: $TAG"
        echo "Increment type: $TYPE"

        if [[ "$TAG" == v* ]]; then
          TAG="${TAG:1}"
        fi

        # Regular expression to match semantic tag
        PATTERN="^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(-((0|[1-9][0-9]*|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9][0-9]*|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*))*))?(\+([0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*))?$"

        # Validate supplied (and parsed) tag
        if ! [[ "$TAG" =~ $PATTERN ]]; then
          echo "Invalid semantic tag"; exit 1
        else
          echo "Numeric tag: $TAG"
        fi

        REGEX='[^0-9]*\([0-9]*\)[.]\([0-9]*\)[.]\([0-9]*\)\([0-9A-Za-z-]*\)'
        MAJOR=$(echo "$TAG" | sed -e "s#$REGEX#\1#")
        MINOR=$(echo "$TAG" | sed -e "s#$REGEX#\2#")
        PATCH=$(echo "$TAG" | sed -e "s#$REGEX#\3#")
        echo "Extracted: Major: $MAJOR  Minor: $MINOR  Patch: $PATCH"

        ### CONTENT RECENTLY ADDED ###

        case "$TYPE" in
          major)
            MAJOR=$((MAJOR+1)
            MINOR="0"
            PATCH="0"
            ;;
          minor)
            MINOR=$((MINOR+1))
            PATCH="0"
            ;;
          patch)
            PATCH=$((PATCH+1))
            ;;
        esac

        INCREMENTED="$MAJOR.$MINOR.$PATCH"
        echo "Incremented: $INCREMENTED"
        echo "tag=${TAG}" >> $GITHUB_OUTPUT

        #SHELLCODEEND
