---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2024 The Linux Foundation <https://linuxfoundation.org>

name: "🏷️ Increment Semantic Tag"

inputs:
  tag:
    description: "The existing semantic tag to be incremented"
    required: true
  type:
    description: "The type of bump to perform [ major, minor, patch ]"
    required: false
    default: "patch"
#   options: [major, minor, patch]

outputs:
  incremented:
    description: "The semantic tag after being incremented"
    value: ${{ steps.increment.outputs.incremented }}

runs:
  using: "composite"
  steps:
    - name: "🏷️ Increment tag"
      id: increment
      shell: bash
      run: |
        TAG=${{ inputs.tag }}
        TYPE=${{ inputs.type }}
        if [ ! "$TYPE" = "major" ] && \
           [ ! "$TYPE" = "minor" ] && \
           [ ! "$TYPE" = "patch" ]; then
           echo "Invalid bump type specified"; exit 1
        fi
