---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2024 The Linux Foundation <https://linuxfoundation.org>

name: "🧪 Validate GitHub Actions"

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, edited, synchronize, closed]
    paths: [".github/**", ".github/actions/**", ".github/workflows/**"]
    branches:
      - "*"

env:
  DEFAULT-PYTHON: "3.10"
  ARTEFACTS: "dist"
  # Configures publishing to PyPI
  PUBLISH: "true"

jobs:
  ### Test Individual Composite Actions ###

  test:
    name: "Individual Synthetic Tests"
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
    continue-on-error: true
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4
        with:
          # Does not currently work: https://github.com/actions/checkout/issues/1471
          fetch-tags: true
          # The semantic-tag-latest action  currently contains a workaround for this behaviour

      - name: "Action: repository-classify-content"
        id: repository-classify-content
        # yamllint disable-line rule:line-length
        uses: os-climate/devops-reusable-workflows/.github/actions/repository-classify-content@main

      - name: "Action: python-twine-check"
        id: python-twine-check
        # yamllint disable-line rule:line-length
        uses: os-climate/devops-reusable-workflows/.github/actions/python-twine-check@main
        with:
          path: "tests/twine"

      - name: "Action: semantic-tag-latest"
        id: semantic-tag-latest
        # yamllint disable-line rule:line-length
        uses: os-climate/devops-reusable-workflows/.github/actions/semantic-tag-latest@main

      - name: "Action: semantic-tag-increment"
        id: semantic-tag-increment
        # yamllint disable-line rule:line-length
        uses: os-climate/devops-reusable-workflows/.github/actions/semantic-tag-increment@main
        with:
          tag: "${{ steps.semantic-tag-latest.outputs.tag }}"
          type: "minor"

      - name: "Action: url-validity-check"
        id: url-validity-check
        # yamllint disable-line rule:line-length
        uses: os-climate/devops-reusable-workflows/.github/actions/url-validity-check@main
        with:
          prefix: "https://test.pypi.org/project"
          string: "/ITR"
          suffix: "/"

      - name: "Action: github-repo-metadata"
        id: github-repo-metadata
        # yamllint disable-line rule:line-length
        uses: os-climate/devops-reusable-workflows/.github/actions/github-repo-metadata@main
