---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2024 The Linux Foundation <https://linuxfoundation.org>

name: "♻️ Update Dependencies"

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 1 * *"
  pull_request:
    types: [opened, reopened, edited, synchronize, closed]
    branches:
      - "**/**"
      - "!update-devops-tooling"
      - "!**/update-pdm-lock"

env:
  DEFAULT-PYTHON: "3.10"

jobs:
  update-dependencies:
    name: "🐍 Python"
    runs-on: ubuntu-latest
    permissions:
      # IMPORTANT: mandatory to raise the PR
      id-token: write
      pull-requests: write
      repository-projects: write
      contents: write

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.default-python }}

      - name: "Update Python dependencies"
        uses: pdm-project/update-deps-action@v1.9
        with:
          sign-off-commit: "true"
          token: ${{ github.token }}
          commit-message: "Chore: Update dependencies and pdm.lock [skip ci]"
          pr-title: "Update Python module dependencies"
          update-strategy: eager
          # Whether to install PDM plugins before update
          install-plugins: "false"
