---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2024 The Linux Foundation <https://linuxfoundation.org>

name: "🧪 Test Composite Actions"

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  push:
    branches: [main, master]
    paths: [".github/actions/**", ".github/workflows/**"]

### TESTS ###

jobs:
  get-python-versions:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.parse-project-metadata.outputs.python-matrix-versions }}

    steps:
      - uses: actions/checkout@v4

      - name: "Populate environment variables"
        id: parse-project-metadata
        # yamllint disable-line rule:line-length
        uses: os-climate/devops-reusable-workflows/.github/actions/python-versions-matrix@main

  test:
    name: "Testing: Composite Actions"
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4
        with:
          # Does not current work: https://github.com/actions/checkout/issues/1471
          fetch-tags: true

      - name: "latest-semantic-tag"
        id: test-latest-semantic-tag
        # yamllint disable-line rule:line-length
        uses: os-climate/devops-reusable-workflows/.github/actions/latest-semantic-tag@main

      - name: "increment-semantic-tag"
        id: test-increment-semantic-tag
        # yamllint disable-line rule:line-length
        uses: os-climate/devops-reusable-workflows/.github/actions/increment-semantic-tag@main
